### PR TITLE
Fix project update

### LINKED ISSUE #44: Packet provider crash
### Provider Version
1.2

### Terraform Version
0.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- packet_project
- packet_ssh_key

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
I'm following along from https://www.terraform.io/docs/providers/packet/index.html
```
$ cat main.tf 
variable "packet_api_key" {}
variable "packet_project_name" {}

terraform {
  required_version = ">= 0.11.2"
}

provider "packet" {
  auth_token = "${var.packet_api_key}"
}

module "packet_server" {
  source       = "./modules/packet.net/"
  project_name = "${var.packet_project_name}"
}

output "project_name" {
  value = "${var.packet_project_name}"
}

output "project_id" {
  value = "${module.packet_server.project_id}"
}
```

```
$ cat modules/packet.net/packet.net.tf 
variable "project_name" {}

resource "packet_project" "phil" {
  name = "${var.project_name}"
  payment_method = "test"          # Only required for a non-default payment method
  #payment_method = "Phil Was Here"          # Only required for a non-default payment method
}

resource "packet_ssh_key" "key_phil" {
  name       = "pgporada"
  public_key = "${file("${path.module}/../../ssh_keys/packet_pgporada.pub")}"
}

output "project_id" {
  value = "${packet_project.phil.id}"
}

output "project_payment_method" {
  value = "${packet_project.phil.payment_method}"
}
```

### Panic Output
https://gist.github.com/pgporada/c888812d378f8b45553cada9660954aa for payment method of "Phil Was Here"
https://gist.github.com/pgporada/2038ed44fcd62b77a72924a7cbcebbbe for payment method of "test"

I am unsure what the payment method should be if it's not the default. Additionally I get an error, but no crash, if I try to output the payment method when using the default.
```
$ terraform apply -var-file environments/test/test.tfvars
packet_ssh_key.key_phil: Refreshing state... (ID: efc554a2-1b1a-4248-abb6-0c1f7af334f5)

Error: Error running plan: 1 error(s) occurred:

* module.packet_server.output.project_payment_method: Resource 'packet_project.phil' does not have attribute 'payment_method' for variable 'packet_project.phil.payment_method'
```

### Expected Behavior
Not to see a crash

### Actual Behavior
I saw a crash because I entered the payment method as "Phil Was Here". Using "test" will also result in a crash.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```
$ terraform plan -var-file environments/test/test.tfvars 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

packet_ssh_key.key_phil: Refreshing state... (ID: efc554a2-1b1a-4248-abb6-0c1f7af334f5)
packet_project.phil: Refreshing state... (ID: 44c6ee41-daaf-486a-b47c-3e9df14c6bf4)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.packet_server.packet_project.phil
      payment_method: "" => "Phil Was Here"


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
```
$ terraform apply -var-file environments/test/test.tfvars
packet_ssh_key.key_phil: Refreshing state... (ID: efc554a2-1b1a-4248-abb6-0c1f7af334f5)
packet_project.phil: Refreshing state... (ID: 44c6ee41-daaf-486a-b47c-3e9df14c6bf4)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.packet_server.packet_project.phil
      payment_method: "" => "Phil Was Here"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.packet_server.packet_project.phil: Modifying... (ID: 44c6ee41-daaf-486a-b47c-3e9df14c6bf4)
  payment_method: "" => "Phil Was Here"

Error: Error applying plan:

1 error(s) occurred:

* module.packet_server.packet_project.phil: 1 error(s) occurred:

* packet_project.phil: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


panic: interface conversion: interface {} is nil, not string
2018-01-25T15:16:26.783-0500 [DEBUG] plugin.terraform-provider-packet_v1.2.0_x4: 
2018-01-25T15:16:26.783-0500 [DEBUG] plugin.terraform-provider-packet_v1.2.0_x4: goroutine 103 [running]:
2018-01-25T15:16:26.783-0500 [DEBUG] plugin.terraform-provider-packet_v1.2.0_x4: github.com/terraform-providers/terraform-provider-packet/packet.resourcePacketProjectUpdate(0xc42017aaf0, 0xb857a0, 0xc4203cb540, 0x24, 0x1165480)
2018-01-25T15:16:26.783-0500 [DEBUG] plugin.terraform-provider-packet_v1.2.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-packet/packet/resource_packet_project.go:86 +0x37d
2018-01-25T15:16:26.783-0500 [DEBUG] plugin.terraform-
```

### PR DESCRIPTION
**Pull request by t0mk**
This PR fixes update logic for project resource, and adds payment_method_id attribute (and proper handling for it) to the project resource.

fixes #44

### CODE REVIEW

File: packet/resource_packet_project.go [hunk 1]
```diff
@@ -1,10 +1,35 @@
...
 import (
+	"fmt"
+	"path"
+	"regexp"
+
 	"github.com/hashicorp/terraform/helper/schema"
 	"github.com/packethost/packngo"
 )
 
+const uuidRE = "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$"
```
Comment (paultyng) [inline packet/resource_packet_project.go]: I would personally do the `MustCompile` here and just assign it to a var:

```golang
var uuidRE = regexp.MustCompile(...)
```

As it will panic earlier just in case there is a problem.

File: packet/resource_packet_project.go [hunk 2]
```diff
@@ -27,6 +52,12 @@ func resourcePacketProject() *schema.Resource {
 				Type:     schema.TypeString,
 				Computed: true,
 			},
+			"payment_method_id": &schema.Schema{
```
Comment (paultyng) [inline packet/resource_packet_project.go]: You'll probably want to make this case insensitive for diffing?

Comment (paultyng) [reply packet/resource_packet_project.go]: Here is an example using `DiffSuppressFunc`: https://github.com/terraform-providers/terraform-provider-google/pull/1141/files

Comment (t0mk) [reply packet/resource_packet_project.go]: good idea, thanks, I did that. However, I can't add test for the billing methods, we don't have mechanism in place to use dummy ones.

File: packet/resource_packet_project.go (hunk 1 above)
Comment (t0mk) [reply packet/resource_packet_project.go]: thanks. I fixed it.

**Comment by t0mk** [comment]
@paultyng Thanks for your review. I bumped TF, so that I can use the RE StringMatch from Terraform.helpers.validation; and then I rebased this PR. I also fixed your comments from the review.
